/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type {
  FormDto,
  FormEntryDto,
  GetUmbracoFormsDeliveryApiV1DefinitionsIdParams
} from '../schemas/index.js';

import { deliveryInstance } from '../../delivery-client.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUmbracoFormsDeliveryAPI = () => {
const getUmbracoFormsDeliveryApiV1DefinitionsId = (
    id: string,
    params?: GetUmbracoFormsDeliveryApiV1DefinitionsIdParams,
 options?: SecondParameter<typeof deliveryInstance<FormDto>>,) => {
      return deliveryInstance<FormDto>(
      {url: `/umbraco/forms/delivery/api/v1/definitions/${id}`, method: 'GET',
        params
    },
      options);
    }
  
const postUmbracoFormsDeliveryApiV1EntriesId = (
    id: string,
    formEntryDto: FormEntryDto,
 options?: SecondParameter<typeof deliveryInstance<void>>,) => {
      return deliveryInstance<void>(
      {url: `/umbraco/forms/delivery/api/v1/entries/${id}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: formEntryDto
    },
      options);
    }
  
return {getUmbracoFormsDeliveryApiV1DefinitionsId,postUmbracoFormsDeliveryApiV1EntriesId}};
export type GetUmbracoFormsDeliveryApiV1DefinitionsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUmbracoFormsDeliveryAPI>['getUmbracoFormsDeliveryApiV1DefinitionsId']>>>
export type PostUmbracoFormsDeliveryApiV1EntriesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUmbracoFormsDeliveryAPI>['postUmbracoFormsDeliveryApiV1EntriesId']>>>
