/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventMessageTypeModel = {
  Default: 'Default',
  Info: 'Info',
  Error: 'Error',
  Success: 'Success',
  Warning: 'Warning',
} as const;
