/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type { FormFieldDtoCondition } from './formFieldDtoCondition.js';
import type { FormFieldDtoFileUploadOptions } from './formFieldDtoFileUploadOptions.js';
import type { FormFieldPrevalueDto } from './formFieldPrevalueDto.js';
import type { FormFieldDtoSettings } from './formFieldDtoSettings.js';
import type { FormFieldTypeDto } from './formFieldTypeDto.js';

export interface FormFieldDto {
  id: string;
  caption: string;
  /** @nullable */
  helpText?: string | null;
  /** @nullable */
  cssClass?: string | null;
  alias: string;
  required: boolean;
  /** @nullable */
  requiredErrorMessage?: string | null;
  /** @nullable */
  pattern?: string | null;
  /** @nullable */
  patternInvalidErrorMessage?: string | null;
  /** @nullable */
  condition?: FormFieldDtoCondition;
  /** @nullable */
  fileUploadOptions?: FormFieldDtoFileUploadOptions;
  preValues: FormFieldPrevalueDto[];
  settings: FormFieldDtoSettings;
  type: FormFieldTypeDto;
}
