/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type { FormPageDtoCondition } from './formPageDtoCondition.js';
import type { FormFieldsetDto } from './formFieldsetDto.js';

export interface FormPageDto {
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  condition?: FormPageDtoCondition;
  fieldsets: FormFieldsetDto[];
}
