/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type { FormFieldIndication } from './formFieldIndication.js';
import type { FormDtoGotoPageOnSubmitRoute } from './formDtoGotoPageOnSubmitRoute.js';
import type { FormPageDto } from './formPageDto.js';
import type { FormValidationRuleDto } from './formValidationRuleDto.js';

export interface FormDto {
  id: string;
  name: string;
  indicator: string;
  /** @nullable */
  cssClass?: string | null;
  /** @nullable */
  nextLabel?: string | null;
  /** @nullable */
  previousLabel?: string | null;
  /** @nullable */
  submitLabel?: string | null;
  disableDefaultStylesheet: boolean;
  fieldIndicationType: FormFieldIndication;
  hideFieldValidation: boolean;
  /** @nullable */
  messageOnSubmit?: string | null;
  messageOnSubmitIsHtml: boolean;
  showValidationSummary: boolean;
  /** @nullable */
  gotoPageOnSubmit?: string | null;
  /** @nullable */
  gotoPageOnSubmitRoute?: FormDtoGotoPageOnSubmitRoute;
  pages: FormPageDto[];
  validationRules: FormValidationRuleDto[];
}
