/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */

export interface CreateFolderModel {
  id: string;
  /** @nullable */
  parentId?: string | null;
  /** @minLength 1 */
  name: string;
}
