/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { DataTypeDetailConfigurationData } from './dataTypeDetailConfigurationData.js';

export interface DataTypeDetail {
  id: number;
  key: string;
  name: string;
  configurationData: DataTypeDetailConfigurationData;
}
