/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FieldDataType } from './fieldDataType.js';

export interface DataSourceWizardFieldMapping {
  key: string;
  name: string;
  include: boolean;
  prevalueKeyField: string;
  prevalueValueField: string;
  prevalueSource: string;
  availablePrevalueValueFields: string[];
  isForeignKey: boolean;
  isMandatory: boolean;
  dataType: FieldDataType;
  defaultValue: string;
  fieldTypeId: string;
  isPrimaryKey: boolean;
  allowNulls: boolean;
}
