/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { DocumentReferenceResponseModelType } from './documentReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';

export interface DocumentReferenceResponseModel {
  $type: DocumentReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  published?: boolean | null;
  documentType: TrackedReferenceDocumentTypeModel;
  variants: DocumentVariantItemResponseModel[];
}
