/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { DocumentVariantStateModel } from './documentVariantStateModel.js';

export interface DocumentVariantItemResponseModel {
  name: string;
  /** @nullable */
  culture?: string | null;
  readonly id: string;
  flags: FlagModel[];
  state: DocumentVariantStateModel;
}
