/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { DocumentTypePropertyTypeReferenceResponseModelType } from './documentTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';

export interface DocumentTypePropertyTypeReferenceResponseModel {
  $type: DocumentTypePropertyTypeReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  documentType: TrackedReferenceDocumentTypeModel;
}
