/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FieldsetContainer } from './fieldsetContainer.js';
import type { FieldSetCondition } from './fieldSetCondition.js';

export interface FieldSet {
  /** @nullable */
  caption?: string | null;
  sortOrder: number;
  id: string;
  page: string;
  containers: FieldsetContainer[];
  /** @nullable */
  condition?: FieldSetCondition;
}
