/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */

export type FieldConditionRuleOperator = typeof FieldConditionRuleOperator[keyof typeof FieldConditionRuleOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldConditionRuleOperator = {
  Is: 'Is',
  IsNot: 'IsNot',
  GreaterThen: 'GreaterThen',
  LessThen: 'LessThen',
  Contains: 'Contains',
  ContainsIgnoreCase: 'ContainsIgnoreCase',
  StartsWith: 'StartsWith',
  StartsWithIgnoreCase: 'StartsWithIgnoreCase',
  EndsWith: 'EndsWith',
  EndsWithIgnoreCase: 'EndsWithIgnoreCase',
  NotContains: 'NotContains',
  NotContainsIgnoreCase: 'NotContainsIgnoreCase',
  NotStartsWith: 'NotStartsWith',
  NotStartsWithIgnoreCase: 'NotStartsWithIgnoreCase',
  NotEndsWith: 'NotEndsWith',
  NotEndsWithIgnoreCase: 'NotEndsWithIgnoreCase',
} as const;
