/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FieldConditionProperty } from './fieldConditionProperty.js';
import type { FieldSettings } from './fieldSettings.js';
import type { FieldPrevalue } from './fieldPrevalue.js';
import type { AllowedUploadType } from './allowedUploadType.js';

export interface Field {
  caption: string;
  /** @nullable */
  tooltip?: string | null;
  /** @nullable */
  cssClass?: string | null;
  alias: string;
  id: string;
  fieldTypeId: string;
  prevalueSourceId: string;
  /** @nullable */
  dataSourceFieldKey?: string | null;
  containsSensitiveData: boolean;
  mandatory: boolean;
  /** @nullable */
  regex?: string | null;
  /** @nullable */
  requiredErrorMessage?: string | null;
  /** @nullable */
  invalidErrorMessage?: string | null;
  /** @nullable */
  condition?: FieldConditionProperty;
  settings: FieldSettings;
  preValues: FieldPrevalue[];
  /** @nullable */
  allowedUploadTypes?: AllowedUploadType[] | null;
  allowMultipleFileUploads: boolean;
}
