/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FieldConditionActionType } from './fieldConditionActionType.js';
import type { FieldConditionLogicType } from './fieldConditionLogicType.js';
import type { FieldConditionRule } from './fieldConditionRule.js';

export interface FieldCondition {
  id: string;
  enabled: boolean;
  actionType: FieldConditionActionType;
  logicType: FieldConditionLogicType;
  rules: FieldConditionRule[];
}
