/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type { FormFieldsetDtoCondition } from './formFieldsetDtoCondition.js';
import type { FormFieldsetColumnDto } from './formFieldsetColumnDto.js';

export interface FormFieldsetDto {
  id: string;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  condition?: FormFieldsetDtoCondition;
  columns: FormFieldsetColumnDto[];
}
