/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */
import type { FormEntryDtoValues } from './formEntryDtoValues.js';
import type { FormEntryDtoAdditionalData } from './formEntryDtoAdditionalData.js';

export interface FormEntryDto {
  values: FormEntryDtoValues;
  /** @nullable */
  contentId?: string | null;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  additionalData?: FormEntryDtoAdditionalData;
}
