/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FormDataSourceSettings } from './formDataSourceSettings.js';

export interface FormDataSource {
  id: string;
  readonly unique: string;
  readonly entityType: string;
  name: string;
  created: string;
  /** @nullable */
  createdBy?: number | null;
  /** @nullable */
  createdByName?: string | null;
  updated: string;
  /** @nullable */
  updatedBy?: number | null;
  /** @nullable */
  updatedByName?: string | null;
  settings: FormDataSourceSettings;
  formDataSourceTypeId: string;
  valid: boolean;
}
