/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { Page } from './page.js';
import type { ValidationRule } from './validationRule.js';
import type { FormFieldIndication } from './formFieldIndication.js';
import type { RecordFieldDisplay } from './recordFieldDisplay.js';
import type { FormDesignDatasource } from './formDesignDatasource.js';
import type { MultiPageNavigationOption } from './multiPageNavigationOption.js';
import type { FormWorkflows } from './formWorkflows.js';

export interface FormDesign {
  /** @minLength 1 */
  name: string;
  created: string;
  /** @nullable */
  createdBy?: number | null;
  /** @nullable */
  createdByName?: string | null;
  updated: string;
  /** @nullable */
  updatedBy?: number | null;
  /** @nullable */
  updatedByName?: string | null;
  pages: Page[];
  validationRules: ValidationRule[];
  id: string;
  readonly unique: string;
  /** @nullable */
  readonly parentUnique?: string | null;
  readonly entityType: string;
  fieldIndicationType: FormFieldIndication;
  indicator: string;
  showValidationSummary: boolean;
  hideFieldValidation: boolean;
  requiredErrorMessage: string;
  invalidErrorMessage: string;
  /** @nullable */
  messageOnSubmit?: string | null;
  messageOnSubmitIsHtml: boolean;
  /** @nullable */
  goToPageOnSubmit?: string | null;
  /** @nullable */
  xPathOnSubmit?: string | null;
  manualApproval: boolean;
  storeRecordsLocally: boolean;
  /** @nullable */
  autocompleteAttribute?: string | null;
  displayDefaultFields: boolean;
  selectedDisplayFields: RecordFieldDisplay[];
  daysToRetainSubmittedRecordsFor: number;
  daysToRetainApprovedRecordsFor: number;
  daysToRetainRejectedRecordsFor: number;
  /** @nullable */
  cssClass?: string | null;
  disableDefaultStylesheet: boolean;
  /** @nullable */
  datasource?: FormDesignDatasource;
  /** @nullable */
  submitLabel?: string | null;
  /** @nullable */
  nextLabel?: string | null;
  /** @nullable */
  prevLabel?: string | null;
  /** @nullable */
  folderId?: string | null;
  nodeId: number;
  showPagingOnMultiPageForms: MultiPageNavigationOption;
  pagingDetailsFormat: string;
  pageCaptionFormat: string;
  showSummaryPageOnMultiPageForms: boolean;
  /** @nullable */
  summaryLabel?: string | null;
  formWorkflows: FormWorkflows;
  path: string;
}
