/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FormTreeItemResponseModelParent } from './formTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface FormTreeItemResponseModel {
  hasChildren: boolean;
  id: string;
  /** @nullable */
  parent?: FormTreeItemResponseModelParent;
  flags: FlagModel[];
  name: string;
  isFolder: boolean;
  path: string;
  icon: string;
}
