/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Delivery API
 * Describes the Umbraco Forms Delivery API available for rendering and submitting forms. You can find out more about the API in [the documentation](https://docs.umbraco.com/umbraco-forms/developer/ajaxforms)
 * OpenAPI spec version: Latest
 */

export type GetUmbracoFormsDeliveryApiV1DefinitionsIdParams = {
/**
 * The Id of the content page on which the form is hosted.
 */
contentId?: string;
/**
 * The culture code for the form's localization context.
 */
culture?: string;
/**
 * Additional data provided when rendering the form.
 */
additionalData?: {[key: string]: string};
};
