/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { MediaTypePropertyTypeReferenceResponseModelType } from './mediaTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMediaTypeModel } from './trackedReferenceMediaTypeModel.js';

export interface MediaTypePropertyTypeReferenceResponseModel {
  $type: MediaTypePropertyTypeReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  mediaType: TrackedReferenceMediaTypeModel;
}
