/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { MediaValueResponseModelValue } from './mediaValueResponseModelValue.js';

export interface MediaValueResponseModel {
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  segment?: string | null;
  /** @minLength 1 */
  alias: string;
  /** @nullable */
  value?: MediaValueResponseModelValue;
  /** @minLength 1 */
  editorAlias: string;
}
