/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */

export type MemberTypePropertyTypeReferenceResponseModelType = typeof MemberTypePropertyTypeReferenceResponseModelType[keyof typeof MemberTypePropertyTypeReferenceResponseModelType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberTypePropertyTypeReferenceResponseModelType = {
  MemberTypePropertyTypeReferenceResponseModel: 'MemberTypePropertyTypeReferenceResponseModel',
} as const;
