/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { MemberReferenceResponseModelType } from './memberReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';

export interface MemberReferenceResponseModel {
  $type: MemberReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  memberType: TrackedReferenceMemberTypeModel;
}
