/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { DefaultReferenceResponseModel } from './defaultReferenceResponseModel.js';
import type { DocumentReferenceResponseModel } from './documentReferenceResponseModel.js';
import type { DocumentTypePropertyTypeReferenceResponseModel } from './documentTypePropertyTypeReferenceResponseModel.js';
import type { MediaReferenceResponseModel } from './mediaReferenceResponseModel.js';
import type { MediaTypePropertyTypeReferenceResponseModel } from './mediaTypePropertyTypeReferenceResponseModel.js';
import type { MemberReferenceResponseModel } from './memberReferenceResponseModel.js';
import type { MemberTypePropertyTypeReferenceResponseModel } from './memberTypePropertyTypeReferenceResponseModel.js';

export type PagedIReferenceResponseModelItemsItem = DefaultReferenceResponseModel | DocumentReferenceResponseModel | DocumentTypePropertyTypeReferenceResponseModel | MediaReferenceResponseModel | MediaTypePropertyTypeReferenceResponseModel | MemberReferenceResponseModel | MemberTypePropertyTypeReferenceResponseModel;
