/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { DataSourceTreeItemResponseModel } from './dataSourceTreeItemResponseModel.js';

export interface PagedDataSourceTreeItemResponseModel {
  total: number;
  items: DataSourceTreeItemResponseModel[];
}
