/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { RecordSorting } from './recordSorting.js';
import type { FormState } from './formState.js';

export type PostExportParams = {
formId?: string;
exportType?: string;
skip?: number;
take?: number;
memberKey?: string;
sortBy?: string;
sortOrder?: RecordSorting;
startDate?: string;
endDate?: string;
filter?: string;
states?: FormState[];
localTimeOffset?: number;
recordId?: string;
};
