/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */

export interface RecordSetActionType {
  id: string;
  name: string;
  alias: string;
  description: string;
  group: string;
  icon: string;
  needsConfirm: boolean;
  confirmMessage: string;
  isAvailableForApprovedRecords: boolean;
}
