/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { SecurityTreeItemResponseModelParent } from './securityTreeItemResponseModelParent.js';
import type { FlagModel } from './flagModel.js';

export interface SecurityTreeItemResponseModel {
  hasChildren: boolean;
  id: string;
  /** @nullable */
  parent?: SecurityTreeItemResponseModelParent;
  flags: FlagModel[];
  name: string;
  isFolder: boolean;
  isGroup: boolean;
  icon: string;
}
