/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */

export interface TrackedReferenceMediaTypeModel {
  id: string;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  name?: string | null;
}
