/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { FlagModel } from './flagModel.js';
import type { UserKindModel } from './userKindModel.js';

export interface UserItemResponseModel {
  id: string;
  flags: FlagModel[];
  name: string;
  avatarUrls: string[];
  kind: UserKindModel;
}
