/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Umbraco Forms Management API
 * Describes the Umbraco Forms Management API available for managing forms data when authenticated as a backoffice user.
 * OpenAPI spec version: Latest
 */
import type { Setting } from './setting.js';

export interface WorkflowTypeWithSettings {
  id: string;
  readonly unique: string;
  readonly entityType: string;
  alias: string;
  name: string;
  description: string;
  icon: string;
  group: string;
  settings: Setting[];
}
