// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk's orval target-major transformer.
// Do not edit by hand — regenerate via `npm run generate`.
/**
 * The Umbraco major version this server's generated tools target.
 *
 * Read from the Umbraco instance this server's tools were generated against,
 * via `GET /umbraco/management/api/v1/server/information`.
 *
 * Reported version: 18.1.1+2d8d866.
 *
 * Passed to `checkUmbracoVersion` at startup, which blocks tool execution when
 * the connected instance's major differs. Set `UMBRACO_EXPECTED_MAJOR` (or
 * `--umbraco-expected-major`) to override it at runtime when deliberately
 * pointing at a different Umbraco major.
 */
export const UMBRACO_TARGET_MAJOR = "18";
