/**
 * Download Export File Tool
 *
 * Downloads a previously generated form record export file.
 *
 * The underlying API returns the raw file as binary content (a File/Blob), which cannot
 * be embedded in an MCP JSON response. This tool therefore returns file metadata only
 * (whether the download succeeded, plus content type and size) rather than the file
 * contents themselves.
 */

import {
  withStandardDecorators,
  createToolResult,
  createToolResultError,
  getApiClient,
  CAPTURE_RAW_HTTP_RESPONSE,
  type ToolDefinition,
  type HttpResponse,
} from "@umbraco-cms/mcp-server-sdk";
import { z } from "zod";
import type { getUmbracoFormsManagementAPI } from "../../../api/generated/umbracoFormsManagementApi.js";
import { getExportQueryParams } from "../../../api/generated/umbracoFormsManagementApi.zod.js";

type ApiClient = ReturnType<typeof getUmbracoFormsManagementAPI>;

const inputSchema = {
  formId: getExportQueryParams.shape.formId.describe(
    "ID of the form the export file belongs to. Use together with fileName to identify the file generated by generate-form-export.",
  ),
  fileName: getExportQueryParams.shape.fileName.describe(
    "Name of the previously generated export file to download, as returned by generate-form-export.",
  ),
};

const outputSchema = z.object({
  success: z.boolean().describe("Whether the file was found and downloaded."),
  formId: z.string().optional(),
  fileName: z.string().optional(),
  contentType: z.string().optional().describe("MIME type of the downloaded file."),
  sizeBytes: z.number().optional().describe("Size of the downloaded file in bytes."),
});

const DownloadExportFileTool = {
  name: "download-export-file",
  description:
    "Downloads a form record export file that was previously generated with " +
    "generate-form-export, identified by formId and fileName. This tool cannot return the " +
    "file's binary contents through MCP — it confirms the download succeeded and reports " +
    "the file's content type and size only. Use this to verify an export file exists and " +
    "is ready, not to retrieve the data itself.",
  inputSchema,
  outputSchema,
  slices: ["read"],
  annotations: {
    readOnlyHint: true,
  },
  handler: async ({ formId, fileName }) => {
    const client = getApiClient<ApiClient>();
    const response = (await client.getExport(
      { formId, fileName },
      CAPTURE_RAW_HTTP_RESPONSE,
    )) as HttpResponse<Blob>;

    if (response.status < 200 || response.status >= 300) {
      return createToolResultError({
        status: response.status,
        detail:
          "Failed to download the export file. Verify formId and fileName match a file previously generated by generate-form-export.",
      });
    }

    const file = response.data as unknown as { type?: string; size?: number } | undefined;

    return createToolResult({
      success: true,
      formId,
      fileName,
      contentType: typeof file?.type === "string" ? file.type : undefined,
      sizeBytes: typeof file?.size === "number" ? file.size : undefined,
    });
  },
} satisfies ToolDefinition<typeof inputSchema, typeof outputSchema>;

export default withStandardDecorators(DownloadExportFileTool);
