import {
  CAPTURE_RAW_HTTP_RESPONSE,
  UmbracoManagementClient,
  type HttpResponse,
} from "@umbraco-cms/mcp-server-sdk";
import {
  getUmbracoFormsManagementAPI,
  type FormDesign,
  type FormSecurityForUser,
} from "../../../../api/generated/umbracoFormsManagementApi.js";
import { purgeForm } from "../../../../../testing/purge.js";

const TEST_RECORD_FORM_NAME = "_Test Record Form";

/**
 * Lightweight helper for the record tool collection. The record tools don't create or
 * delete their own persistent entities — search-records/update-record/get-record-* all
 * need a real, existing Form to operate against (most as a required `formId` path
 * parameter, even when no record actually exists for it yet). This helper creates a
 * throwaway Form for the duration of the record tests and removes it afterward,
 * following the same pattern as ExportTestFormHelper in the export collection.
 *
 * Unlike a full CRUD builder, the created form's ID is known up-front: get-form-scaffold
 * returns a complete FormDesign with its `id` already generated, and postForm (which
 * returns void) doesn't hand back a new one — the scaffold's `id` IS the form's ID once
 * created.
 */
export class RecordTestFormHelper {
  /**
   * Creates a temporary form (using the server's form scaffold) named
   * `_Test Record Form` and returns its ID.
   */
  static async createTestForm(): Promise<string> {
    const client = getUmbracoFormsManagementAPI();

    const scaffoldResponse = (await client.getFormScaffold(
      CAPTURE_RAW_HTTP_RESPONSE,
    )) as HttpResponse<FormDesign>;

    if (scaffoldResponse.status < 200 || scaffoldResponse.status >= 300) {
      throw new Error(
        `Failed to fetch form scaffold: HTTP ${scaffoldResponse.status} ${scaffoldResponse.statusText}`,
      );
    }

    const formDesign: FormDesign = {
      ...scaffoldResponse.data,
      name: TEST_RECORD_FORM_NAME,
    };

    const createResponse = (await client.postForm(
      formDesign,
      CAPTURE_RAW_HTTP_RESPONSE,
    )) as HttpResponse<void>;

    if (createResponse.status < 200 || createResponse.status >= 300) {
      throw new Error(
        `Failed to create test form: HTTP ${createResponse.status} ${createResponse.statusText}`,
      );
    }

    return formDesign.id;
  }

  /**
   * Deletes the temporary form created with createTestForm(). Swallows errors so
   * cleanup never masks a test failure.
   */
  static async deleteTestForm(id: string): Promise<void> {
    if (!id) return;

    await purgeForm(id);
  }

  /** IDs of every field on a form, in design order. */
  static async getFieldIds(formId: string): Promise<string[]> {
    const form = (await getUmbracoFormsManagementAPI().getFormById(formId)) as FormDesign;
    return form.pages.flatMap((page) =>
      page.fieldSets.flatMap((fieldset) =>
        fieldset.containers.flatMap((container) => container.fields.map((field) => field.id)),
      ),
    );
  }

  /**
   * Runs `fn` with the "delete entries" Forms permission granted to the current
   * (API) user, then puts the user's permissions back. Forms gives even
   * administrators every entry permission except that one by default.
   */
  static async withDeleteEntriesPermission<T>(fn: () => Promise<T>): Promise<T> {
    const client = getUmbracoFormsManagementAPI();
    const me = (await UmbracoManagementClient<{ id: string }>(
      { method: "GET", url: "/umbraco/management/api/v1/user/current" },
      CAPTURE_RAW_HTTP_RESPONSE,
    )) as unknown as HttpResponse<{ id: string }>;
    const original = (await client.getSecurityUserByIdFormSecurity(me.data.id)) as FormSecurityForUser;

    await client.putSecurityUserByIdFormSecurity(me.data.id, {
      ...original,
      userSecurity: { ...original.userSecurity, deleteEntries: true },
    });
    try {
      return await fn();
    } finally {
      await client.putSecurityUserByIdFormSecurity(me.data.id, original);
    }
  }

  /**
   * search-records/get-record-metadata return a `schema` array describing every field
   * a record could report a value for, including the built-in "dataConsent" field. That
   * field's `id` is a fresh GUID generated by the server every time a form is scaffolded
   * (unlike the other built-in schema entries, which use stable string ids like "state" or
   * "created"), so it isn't reproducible across test runs. `createSnapshotResult`'s ID
   * normalization only walks a fixed set of known fields and never descends into `schema`,
   * so this recursively blanks any GUID-shaped `id` value before snapshotting.
   */
  static normalizeSchemaIds<T>(data: T): T {
    const guidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

    const walk = (value: unknown): unknown => {
      if (Array.isArray(value)) {
        return value.map(walk);
      }
      if (value && typeof value === "object") {
        const normalized: Record<string, unknown> = { ...(value as Record<string, unknown>) };
        for (const key of Object.keys(normalized)) {
          const fieldValue = normalized[key];
          if (key === "id" && typeof fieldValue === "string" && guidPattern.test(fieldValue)) {
            normalized[key] = "00000000-0000-0000-0000-000000000000";
          } else if (fieldValue && typeof fieldValue === "object") {
            normalized[key] = walk(fieldValue);
          }
        }
        return normalized;
      }
      return value;
    };

    return walk(data) as T;
  }
}

export { TEST_RECORD_FORM_NAME };
