import {
  setupTestEnvironment,
  createMockRequestHandlerExtra,
  createSnapshotResult,
  ExportTestFormHelper,
} from "./setup.js";
import downloadExportFileTool from "../get/download-export-file.js";
import generateFormExportTool from "../post/generate-form-export.js";

const TEST_EXPORT_TYPE = "csvSubmittedValues";

/**
 * KNOWN BLOCKER — escalated, not worked around here.
 *
 * download-export-file downloads a file previously produced by generate-form-export.
 * As documented in generate-form-export.test.ts, generate-form-export currently
 * returns a real, unhandled 500 for any form with zero submitted records — and the
 * Forms Management API has no endpoint to create a form record, so no fileName is
 * ever actually produced to download in this environment. The happy-path test below
 * calls the real generate step first (rather than hardcoding a fileName) and documents
 * the current, real (non-mocked) outcome instead of fabricating a successful download.
 */
describe("download-export-file", () => {
  setupTestEnvironment();

  let formId: string;

  beforeAll(async () => {
    formId = await ExportTestFormHelper.createTestForm();
  });

  afterAll(async () => {
    await ExportTestFormHelper.deleteTestForm(formId);
  });

  it("documents the current outcome of downloading a file generated by generate-form-export (see blocker comment above)", async () => {
    const context = createMockRequestHandlerExtra();

    const generateResult = await generateFormExportTool.handler(
      {
        formId,
        exportType: TEST_EXPORT_TYPE,
        memberKey: undefined,
        sortBy: undefined,
        sortOrder: undefined,
        startDate: undefined,
        endDate: undefined,
        filter: undefined,
        states: undefined,
        recordId: undefined,
        recordIds: undefined,
      },
      context,
    );

    // generate-form-export is currently blocked (see comment above) and never returns
    // a fileName in this environment, so there is no real generated file to download.
    const fileName =
      !generateResult.isError &&
      generateResult.structuredContent &&
      typeof generateResult.structuredContent === "object" &&
      "fileName" in generateResult.structuredContent
        ? (generateResult.structuredContent as { fileName: string }).fileName
        : "generate-form-export-did-not-return-a-file-name.csv";

    const result = await downloadExportFileTool.handler({ formId, fileName }, context);

    expect(createSnapshotResult(result, formId)).toMatchSnapshot();
  });

  it("should return error for a fileName that was never generated", async () => {
    const context = createMockRequestHandlerExtra();

    const result = await downloadExportFileTool.handler(
      { formId, fileName: "_test-does-not-exist.csv" },
      context,
    );

    expect(result.isError).toBe(true);
  });
});
